# Create a ready-to-deploy GitHub Pages (Jekyll) starter for "Wilmington Alliance"
# It includes a remote_theme, sample pages, a blog post, CSS override, and image placeholders.
import os, textwrap, zipfile, pathlib, datetime

base = pathlib.Path("/mnt/data/wilmington-alliance-ghpages")
(base / "_posts").mkdir(parents=True, exist_ok=True)
(base / "assets/css").mkdir(parents=True, exist_ok=True)
(base / "assets/img").mkdir(parents=True, exist_ok=True)

# _config.yml
config = textwrap.dedent("""
title: Wilmington Alliance
description: Projects, notes, and quick grabs by Wilmington Alliance (tone)
url: ""  # set to https://<username>.github.io after publishing
baseurl: ""

# Use an official GitHub Pages theme (no build step required)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Collections / options
markdown: kramdown
highlighter: rouge
timezone: America/New_York

# Navigation (shown via header includes on the theme)
nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: About
    url: /about/

# Social / org metadata
org_name: Wilmington Alliance
org_tagline: Data, Ops, and Cyber for Wilmington
org_logo: /assets/img/wilma-logo.svg

# Defaults (adds layout to pages and posts automatically)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
""").strip()

# index.md
index_md = textwrap.dedent("""
---
layout: home
title: Home
---

![WILMA](/assets/img/wilma-logo.svg)

Welcome to the Wilmington Alliance GitHub Pages site. This is a fast place for:
- Writing about what we are building
- Dropping images and assets to grab quickly
- Linking to dashboards and docs

### Quick Links
- **Knowledge Base** (private/internal, link as needed)
- **WILMA Agent**: internal LM Studio + AnythingLLM setup
- **Contact**: tone

> Tip: Edit this page at `index.md`. Images go under `assets/img/`.
""").strip()

# about.md
about_md = textwrap.dedent("""
---
title: About
permalink: /about/
---

## Wilmington Alliance

We are building community-centered technology for economic mobility in Wilmington, Delaware.

### This Site
- Built with **GitHub Pages** and **Jekyll**
- Theme: **Cayman** (GitHub Pages official)
- Supports Markdown posts under `_posts/`

### How to add a new page
Create a new `.md` file at the repository root with a YAML front matter block:
```markdown
---
title: My Page
permalink: /my-page/
---

Write content in Markdown here.
